alter table SAMPLE_SERVICE add constraint FK_SAMPLE_SERVICE_DETAILING foreign key (DETAILING_ID) references SAMPLE_DETAILING(ID);
create index IDX_SAMPLE_SERVICE_DETAILING on SAMPLE_SERVICE (DETAILING_ID);
